name: idb
description: iDB
publish_to: 'none'
version: 1.0.2+6

environment:
    sdk: '>=2.14.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    clipboard: ^0.1.3
    crypto: ^3.0.3
    cupertino_icons: ^1.0.5
    desktop_window: ^0.4.0
    file_picker: ^5.3.2
    flutter_keyboard_visibility: ^5.4.1
    flutter_mobx: ^2.0.6+5
    flutter_svg: ^2.0.7
    flutter_html: ^3.0.0-beta.2
    get_it: ^7.6.0
    html: ^0.15.4
    http: ^1.1.0
    json_annotation: ^4.8.1
    mime: ^1.0.4
    mobx: ^2.2.0
    package_info_plus: ^4.0.2
    path: ^1.8.3
    path_provider: ^2.0.15
    sentry: ^7.8.0
    sentry_flutter: ^7.8.0
    shared_preferences: ^2.2.0
    url_launcher: ^6.1.12
    uuid: ^3.0.7

dev_dependencies:
    flutter_test:
        sdk: flutter

    build_runner: ^2.4.6
    flutter_lints: ^2.0.2
    json_serializable: ^6.7.1
    build_test: ^2.2.0
    mobx_codegen: ^2.3.0

flutter:
    uses-material-design: true

    fonts:
        - family: Inconsolata
          fonts:
              - asset: assets/fonts/Inconsolata-Bold.ttf
                weight: 700
              - asset: assets/fonts/Inconsolata-Regular.ttf
                weight: 400

    assets:
        - assets/images/
        - assets/images/pics/
        - assets/images/svg/
        - assets/json/
