#!/bin/bash


if [ "$1" == "cleanbuilder" ]
then
clear

flutter packages pub run build_runner clean


elif [ "$1" == "builder" ]
then
clear

flutter pub run build_runner watch --delete-conflicting-outputs


elif [ "$1" == "cleanios" ]
then
clear

flutter clean
rm -rf ios/Runner.xcworkspace
rm -rf ios/.symlinks ios/Pods
rm -f ios/Podfile.lock
rm -f pubspec.lock
rm -f .packages

flutter pub get
cd ios && pod install --repo-update


elif [ "$1" == "deploytoiphone" ]
then
clear
flutter run -t lib/main.dart --release


elif [ "$1" == "buildweb" ]
then
clear
flutter build web --release --web-renderer canvaskit


elif [ "$1" == "deployweb" ]
then
clear

flutter build web --release --web-renderer canvaskit
rsync -avh -e ssh $(pwd)/build/web/  ubuntu@65.21.106.58:/home/ubuntu/idb_flutter/


elif [ "$1" == "test" ]
then
clear

flutter test test/items/image_parsing_test.dart


else
clear

flutter run

fi
